[project]
name = "abalon"
version = "0.1.0"
description = "Primera entrega del proyecto Modular"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "streamlit>=1.52.1",
    "supabase>=2.26.0",
]
